2017-11-29 08:06:04.8867 INFO LiveCollect.Display.Website.Startup Startup.Configuration() called
2017-11-29 08:06:56.3420 INFO LiveCollect.Display.Website.Startup Startup.Configuration() called
2017-11-29 08:07:05.7006 INFO LiveCollect.Display.Website.Controllers.AccountController User logged in: OTP Building Plastics (karen@otpsupplies.co.uk)
2017-11-29 08:07:38.5583 INFO LiveCollect.Display.Website.Controllers.AccountController User logged out: OTP Building Plastics (karen@otpsupplies.co.uk)
2017-11-29 08:28:07.5702 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 08:31:16.5914 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 08:32:23.7663 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 08:34:07.0398 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 08:56:59.2484 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 08:57:44.0123 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 08:58:54.3828 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 09:05:35.3928 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 09:12:01.6833 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 09:18:25.9545 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 09:19:59.5991 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 09:20:13.8505 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 09:21:13.7851 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:9099ccb7-203b-4506-b222-e7be264f6b65
Error Number:2812,State:62,Class:16
2017-11-29 09:21:14.1431 ERROR YPMMS.Display.Website.Controllers.OverviewController System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MachineWithCashValues'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<MultiMapAsync>d__42`8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.MachineRepository.<GetMachinesAsync>d__4.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\MachineRepository.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.MachineDataService.<GetAllMachinesAsync>d__9.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\MachineDataService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.OverviewController.<MachinesDataAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\OverviewController.cs:line 49
ClientConnectionId:39ab24b9-4fad-41b1-acf4-14d6cf49edfc
Error Number:208,State:1,Class:16
2017-11-29 09:21:29.4172 ERROR YPMMS.Display.Website.Controllers.OverviewController System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MachineWithCashValues'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<MultiMapAsync>d__42`8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.MachineRepository.<GetMachinesAsync>d__4.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\MachineRepository.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.MachineDataService.<GetAllMachinesAsync>d__9.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\MachineDataService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.OverviewController.<MachinesDataAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\OverviewController.cs:line 49
ClientConnectionId:8b551760-fead-43b7-8567-b4236d5c2c74
Error Number:208,State:1,Class:16
2017-11-29 09:21:29.9072 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:ecf4e09c-d1a5-42c1-bf26-23d61c6ec5ef
Error Number:2812,State:62,Class:16
2017-11-29 09:22:33.5155 ERROR YPMMS.Display.Website.Controllers.OverviewController System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MachineWithCashValues'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<MultiMapAsync>d__42`8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.MachineRepository.<GetMachinesAsync>d__4.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\MachineRepository.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.MachineDataService.<GetAllMachinesAsync>d__9.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\MachineDataService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.OverviewController.<MachinesDataAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\OverviewController.cs:line 49
ClientConnectionId:da525934-dec6-4e8c-9c54-96214edb92c6
Error Number:208,State:1,Class:16
2017-11-29 09:22:34.0312 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:6bc938ba-f581-4796-b0d8-3318c1ef7a5b
Error Number:2812,State:62,Class:16
2017-11-29 09:22:40.0588 ERROR YPMMS.Display.Website.Controllers.AdminController System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MachineWithCashValues'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<MultiMapAsync>d__42`8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.MachineRepository.<GetMachinesAsync>d__4.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\MachineRepository.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.MachineDataService.<GetAllMachinesAsync>d__9.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\MachineDataService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.AdminController.<MachinesDataAsync>d__7.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\AdminController.cs:line 120
ClientConnectionId:78acd42c-e339-4757-8615-7a2c43102b59
Error Number:208,State:1,Class:16
2017-11-29 09:22:40.3960 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:2c7bcef6-1a1c-41b9-8029-e29d321570c0
Error Number:2812,State:62,Class:16
2017-11-29 09:22:50.4010 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:895e3bb3-2d8f-414d-9f74-81d9a1e372fc
Error Number:2812,State:62,Class:16
2017-11-29 09:22:55.0347 ERROR YPMMS.Display.Website.Controllers.AdminController System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MachineWithCashValues'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<MultiMapAsync>d__42`8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.MachineRepository.<GetMachinesAsync>d__4.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\MachineRepository.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.MachineDataService.<GetAllMachinesAsync>d__9.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\MachineDataService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.AdminController.<MachinesDataAsync>d__7.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\AdminController.cs:line 120
ClientConnectionId:58542cda-4858-4dd0-a416-3390d8ff3866
Error Number:208,State:1,Class:16
2017-11-29 09:22:55.3125 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:1b69688f-d93a-4cbd-9d92-d4a87713bf07
Error Number:2812,State:62,Class:16
2017-11-29 09:22:57.9217 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:d85912a1-5c7d-47ac-9fd8-f38b08b2a2d4
Error Number:2812,State:62,Class:16
2017-11-29 09:23:04.5690 ERROR YPMMS.Display.Website.Controllers.AdminController System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MachineWithCashValues'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<MultiMapAsync>d__42`8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.MachineRepository.<GetMachinesAsync>d__4.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\MachineRepository.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.MachineDataService.<GetAllMachinesAsync>d__9.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\MachineDataService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.AdminController.<MachinesDataAsync>d__7.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\AdminController.cs:line 120
ClientConnectionId:3377d71b-79ef-4298-95bd-daf9f5f732a5
Error Number:208,State:1,Class:16
2017-11-29 09:23:04.7374 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:bdd00814-4522-4b0b-a9d0-fe49e97ba440
Error Number:2812,State:62,Class:16
2017-11-29 09:23:14.1173 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:3f97109c-acd4-406f-8d50-527565b831c6
Error Number:2812,State:62,Class:16
2017-11-29 09:23:14.6032 ERROR YPMMS.Display.Website.Controllers.OverviewController System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MachineWithCashValues'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<MultiMapAsync>d__42`8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.MachineRepository.<GetMachinesAsync>d__4.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\MachineRepository.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.MachineDataService.<GetAllMachinesAsync>d__9.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\MachineDataService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.OverviewController.<MachinesDataAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\OverviewController.cs:line 49
ClientConnectionId:11c80ad7-a4c5-4233-b843-970776339784
Error Number:208,State:1,Class:16
2017-11-29 09:37:10.4162 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 09:37:21.1890 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 09:37:28.6271 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:ca76c01a-b374-439a-a573-275a9a17a343
Error Number:2812,State:62,Class:16
2017-11-29 09:37:29.0664 ERROR YPMMS.Display.Website.Controllers.OverviewController System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'MachineWithCashValues'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<MultiMapAsync>d__42`8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.MachineRepository.<GetMachinesAsync>d__4.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\MachineRepository.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.MachineDataService.<GetAllMachinesAsync>d__9.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\MachineDataService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.OverviewController.<MachinesDataAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\OverviewController.cs:line 49
ClientConnectionId:3dc369ae-dbcb-4d55-9e5b-37505d54f9cc
Error Number:208,State:1,Class:16
2017-11-29 10:26:51.3629 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 10:27:11.3455 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 10:29:36.1551 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 10:29:52.6642 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 10:30:30.7914 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 10:30:55.4313 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 10:33:17.1319 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 10:35:26.6345 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 10:42:06.6888 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 10:42:48.5700 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 10:48:00.5082 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 10:48:12.9471 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 10:54:35.5474 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 10:54:48.3626 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 10:57:55.0029 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 10:58:06.6230 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:01:41.1734 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 11:01:50.8174 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:03:19.6322 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 11:03:35.3943 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:04:40.7659 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 11:05:03.5762 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:05:04.6400 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:80e5ea39-1632-4ef8-a875-b7818dc47700
Error Number:2812,State:62,Class:16
2017-11-29 11:05:55.8135 INFO YPMMS.Display.Website.Controllers.AccountController User logged out:  (dclayton@innovative-technology.com)
2017-11-29 11:10:31.7753 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 11:10:39.5736 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:11:09.2235 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:17ab9526-3e9e-49ca-a316-ad52b0d4fd63
Error Number:2812,State:62,Class:16
2017-11-29 11:12:09.9997 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:55a64f08-d77e-428f-8d77-8c8b255128e5
Error Number:2812,State:62,Class:16
2017-11-29 11:14:48.3001 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:cbe7fef5-1b91-40bf-bce2-2deec8a51799
Error Number:2812,State:62,Class:16
2017-11-29 11:15:52.2097 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:b4e77afd-6e7d-45dc-b96b-b63d6e066997
Error Number:2812,State:62,Class:16
2017-11-29 11:16:27.2424 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:13f4d1eb-beda-431d-aa20-e50ff25612a8
Error Number:2812,State:62,Class:16
2017-11-29 11:19:49.1733 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:b3745ca2-5152-4de9-9875-4b6421b1d13f
Error Number:2812,State:62,Class:16
2017-11-29 11:21:51.6273 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:829273cf-ee95-441c-a132-2aecdae67cb7
Error Number:2812,State:62,Class:16
2017-11-29 11:37:09.3081 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 11:37:27.9315 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:38:01.9926 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:a724c912-fbda-498b-9cdb-6fed02c3fd67
Error Number:2812,State:62,Class:16
2017-11-29 11:39:15.2086 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:ee182653-2272-4004-b779-446f141d271c
Error Number:2812,State:62,Class:16
2017-11-29 11:45:03.9419 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 11:45:11.7609 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:45:31.2842 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:52431158-b186-42c6-ad37-bde7a80e3c28
Error Number:2812,State:62,Class:16
2017-11-29 11:46:43.2570 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:ed449f1a-b70b-4ecf-85d1-e2c216ecb21d
Error Number:2812,State:62,Class:16
2017-11-29 11:47:50.1429 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 11:48:02.6832 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:48:10.8216 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:729e29a3-076f-4bcb-bfd7-c8f7b9886daa
Error Number:2812,State:62,Class:16
2017-11-29 11:49:12.7886 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:2095a479-4f59-4fd0-8f7b-45c6b13d8fc3
Error Number:2812,State:62,Class:16
2017-11-29 11:57:20.8249 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 11:57:27.2216 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:57:32.5939 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:d90fbb7d-9786-46ec-8ac6-55a3cb79add6
Error Number:2812,State:62,Class:16
2017-11-29 11:58:05.4033 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:0f5a9ce4-1f6a-4240-a1f7-94de8e9fa0f9
Error Number:2812,State:62,Class:16
2017-11-29 11:58:50.5947 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 11:58:56.2192 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 11:59:01.7389 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:5b914fd1-98ca-4a3a-adeb-f5d5492b0c4c
Error Number:2812,State:62,Class:16
2017-11-29 11:59:37.7510 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:30c15fa5-4d95-4ac1-b97c-ed99bd6d9a8b
Error Number:2812,State:62,Class:16
2017-11-29 12:00:14.8700 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:bf416d2b-5897-4171-952b-959473f08ff8
Error Number:2812,State:62,Class:16
2017-11-29 13:08:14.1420 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 13:08:22.9558 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 13:10:11.2205 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:ea171284-dc47-4832-9096-dba4917ac137
Error Number:2812,State:62,Class:16
2017-11-29 13:18:56.1228 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 13:19:04.1440 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 13:19:29.2690 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:8cbafc79-801d-4bc6-9bb1-cc952f5da604
Error Number:2812,State:62,Class:16
2017-11-29 13:20:06.8525 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:ecfd31dc-f362-47b3-873e-e7f49b298f26
Error Number:2812,State:62,Class:16
2017-11-29 13:21:07.9581 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:a6fd9e3b-2daa-41fe-a5c0-f76e22facca0
Error Number:2812,State:62,Class:16
2017-11-29 13:21:35.8460 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:add1a5b7-3b96-4fb2-854d-ffb6598581d5
Error Number:2812,State:62,Class:16
2017-11-29 13:25:38.1777 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:e652a95c-de51-4236-910a-9cfb1f7f4e9c
Error Number:2812,State:62,Class:16
2017-11-29 13:26:19.1302 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:83d43d12-2b6f-4a32-96bc-c3e96fbed5cd
Error Number:2812,State:62,Class:16
2017-11-29 13:27:07.2807 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:6910ffee-00d4-46ea-96dc-66fe94edef83
Error Number:2812,State:62,Class:16
2017-11-29 13:31:13.4072 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 13:31:31.5343 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 13:31:42.4402 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:ab85af30-6744-4e39-8a0f-ffaedc53ddca
Error Number:2812,State:62,Class:16
2017-11-29 13:33:27.8345 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:cc63ea10-aee6-4b5d-98bd-749750a0c0e0
Error Number:2812,State:62,Class:16
2017-11-29 13:33:59.2023 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:13f0559b-1f9f-4057-b913-b71ed655450f
Error Number:2812,State:62,Class:16
2017-11-29 13:35:42.8317 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:c7a76c31-8d06-4ed8-b818-26da3fb3828b
Error Number:2812,State:62,Class:16
2017-11-29 13:36:46.9290 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:75970e7c-9983-49b3-8649-f0f45a34f612
Error Number:2812,State:62,Class:16
2017-11-29 13:38:17.2705 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 13:38:26.1307 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 13:38:28.0357 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:ef86cffc-2579-4898-ac61-7fb5147ad951
Error Number:2812,State:62,Class:16
2017-11-29 13:39:58.2569 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:7cf21715-e30c-4f64-8772-5dcaf36bf5fc
Error Number:2812,State:62,Class:16
2017-11-29 13:40:46.9886 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 13:41:01.9890 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.NullReferenceException: Object reference not set to an instance of an object.
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
2017-11-29 13:50:27.1558 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 13:52:26.6203 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 13:52:27.7626 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:73bc0283-a191-4732-8de9-49ac07f8566b
Error Number:2812,State:62,Class:16
2017-11-29 13:54:18.2181 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:a668eba2-825f-4c94-8606-113fdb14ed70
Error Number:2812,State:62,Class:16
2017-11-29 13:56:25.8167 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:3fa1b9cd-c6bc-43d0-842b-15486602e70a
Error Number:2812,State:62,Class:16
2017-11-29 13:58:04.4652 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:095d2d02-aa04-4a9b-83c4-88584e91ae0b
Error Number:2812,State:62,Class:16
2017-11-29 13:58:41.4145 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:aba8ea57-e065-4c67-9a51-7fe551446ac2
Error Number:2812,State:62,Class:16
2017-11-29 13:58:48.9047 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:476aa8c9-8169-4ae0-964d-9d6e0e2db4fd
Error Number:2812,State:62,Class:16
2017-11-29 13:58:59.5882 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:f244c3dc-4ccf-4f6e-a372-be8b695f52c9
Error Number:2812,State:62,Class:16
2017-11-29 13:59:10.8542 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:18194ba0-ffd8-4b9e-9273-f3377a9af0c1
Error Number:2812,State:62,Class:16
2017-11-29 13:59:13.5442 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:7c7a2711-6a6f-461d-ac6b-fcb13a71e190
Error Number:2812,State:62,Class:16
2017-11-29 13:59:17.8605 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:1cb78fd5-9a1a-45cd-a6d4-cd1492d8c064
Error Number:2812,State:62,Class:16
2017-11-29 14:14:19.5798 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 14:14:41.3039 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 14:14:44.2658 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:9c9fd727-22cb-44c5-a021-9c918c056e96
Error Number:2812,State:62,Class:16
2017-11-29 14:18:58.2287 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 14:19:23.8349 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 14:19:26.2710 ERROR YPMMS.Display.Website.Controllers.SystemEventsController System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'GetSystemEventsForUser'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Data.Repository.Repositories.SystemEventRepository.<GetSystemEventsForUserAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Data.Repository\Repositories\SystemEventRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Domain.Service.Services.SystemEventDataService.<GetLatestSystemEventsForUserAsync>d__3.MoveNext() in C:\YPMMS\YPMMS.Domain.Service\Services\SystemEventDataService.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YPMMS.Display.Website.Controllers.SystemEventsController.<GetLatestSystemEventsAsync>d__1.MoveNext() in C:\YPMMS\YPMMS.Display.Website\Controllers\SystemEventsController.cs:line 56
ClientConnectionId:fb263e0e-8aa5-4343-8932-a808b05852c8
Error Number:2812,State:62,Class:16
2017-11-29 14:27:01.6307 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 14:27:13.3783 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 14:28:50.1155 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 14:28:55.9596 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 14:31:23.1248 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 14:31:28.9291 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 14:35:59.9383 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 14:36:21.9225 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 15:23:24.2913 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 15:23:28.4771 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 15:47:54.5706 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 15:48:16.2733 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 16:04:10.7996 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 16:04:17.1281 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 16:05:50.7319 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 16:06:02.3125 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
2017-11-29 16:08:26.0340 INFO YPMMS.Display.Website.Startup Startup.Configuration() called
2017-11-29 16:25:04.5755 INFO YPMMS.Display.Website.Controllers.AccountController User logged in:  (dclayton@innovative-technology.com)
